apiVersion: apps/v1
kind: Deployment
metadata:
  name: logo-express-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: uday0710/logo-express:build-1
          ports:
            - containerPort: 80